name: Build and run openai-code-review by main maven jar

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Copy openai-code-review-sdk JAR
        run: mvn dependency:copy -Dartifact=org.rdx.sdk:openai-code-review-sdk:1.0 -DoutputDirectory=./libs -Dmdep.stripVersion=false

      - name: List files in libs directory
        run: ls -la ./libs

      - name: Run code review
        run: java -jar ./libs/openai-code-review-sdk-1.0.jar